name       : lightdm-settings
version    : 1.2.5
release    : 2
source     :
    - https://github.com/linuxmint/lightdm-settings/archive/1.2.5.tar.gz : dd53ec0097f60f296df9b818b06f6d5891c45969aede6f6b237e74d31e58e4ab
license    : GPL-3.0-or-later
component  : system.utils
summary    : A configuration tool for the LightDM display manager
description: |
    A configuration tool for the LightDM display manager This tool currently lets users configure slick-greeter.
rundeps    :
    - hicolor-icon-theme
    - python-gobject
    - python-setproctitle
    - python-xapp
    - slick-greeter
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr
    install -Dm00664 $pkgfiles/lighdm-gtk-greeter.conf $installdir/etc/lightdm/lightdm.conf
    cp -R usr $installdir
