name       : lightdm-settings
version    : 1.3.1
release    : 5
source     :
    - https://github.com/linuxmint/lightdm-settings/archive/1.3.1.tar.gz : dca322bd964fcc0e7a0fb4a04b02ccb97ee2b2163567e1edaa9a8872da0484ff
license    : GPL-3.0-or-later
component  : system.utils
summary    : A configuration tool for the LightDM display manager
description: |
    A configuration tool for the LightDM display manager This tool currently lets users configure slick-greeter.
rundeps    :
    - hicolor-icon-theme
    - python-setproctitle
    - python-xapp
    - python3-gobject
    - slick-greeter
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr
    install -Dm00664 $pkgfiles/lighdm-gtk-greeter.conf $installdir/etc/lightdm/lightdm.conf
    cp -R usr $installdir
