name       : lightdm-settings
version    : 1.5.7
release    : 14
source     :
    - https://github.com/linuxmint/lightdm-settings/archive/1.5.7.tar.gz : 71dd46276e3a5101940e4e91d85681e4b4516966aa7195f79f8eb191c898ea2b
homepage   : https://github.com/linuxmint/lightdm-settings
license    : GPL-3.0-or-later
component  : system.utils
summary    : A configuration tool for the LightDM display manager
description: |
    A configuration tool for the LightDM display manager. This tool currently lets users configure slick-greeter.
rundeps    :
    - hicolor-icon-theme
    - python-setproctitle
    - python-xapp
    - slick-greeter
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr
    install -Dm00664 $pkgfiles/lightdm-gtk-greeter.conf $installdir/etc/lightdm/lightdm.conf
    cp -R usr $installdir
