name       : lightdm-settings
version    : 1.8.2
release    : 19
source     :
    - https://github.com/linuxmint/lightdm-settings/archive/refs/tags/1.8.2.tar.gz : 58d5e9a9cb9cb91f876faaa7a85de247e65bbf25accda1139b3c325623e85509
homepage   : https://github.com/linuxmint/lightdm-settings
license    : GPL-3.0-or-later
component  : system.utils
summary    : A configuration tool for the LightDM display manager
description: |
    A configuration tool for the LightDM display manager. This tool currently lets users configure slick-greeter.
rundeps    :
    - hicolor-icon-theme
    - python-packaging
    - python-setproctitle
    - python-xapp
    - slick-greeter
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr
    cp -R usr $installdir
    install -Dm00664 $pkgfiles/lightdm-gtk-greeter.conf $installdir/etc/lightdm/lightdm.conf
