name       : lightdm-settings
version    : 1.2.8
release    : 4
source     :
    - https://github.com/linuxmint/lightdm-settings/archive/1.2.8.tar.gz : 741b4d1f0981db915c07b1acef36c6addf84dd5bd58e45e7169ae163546e2a38
license    : GPL-3.0-or-later
component  : system.utils
summary    : A configuration tool for the LightDM display manager
description: |
    A configuration tool for the LightDM display manager This tool currently lets users configure slick-greeter.
rundeps    :
    - hicolor-icon-theme
    - python3-gobject
    - python-setproctitle
    - python-xapp
    - slick-greeter
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr
    install -Dm00664 $pkgfiles/lighdm-gtk-greeter.conf $installdir/etc/lightdm/lightdm.conf
    cp -R usr $installdir
