name       : lightdm-settings
version    : 1.5.1
release    : 11
source     :
    - https://github.com/linuxmint/lightdm-settings/archive/1.5.1.tar.gz : 8d9cb1d4bde7522ada05781f5e5acc59e4cc4ce6ff815fcd115b7b91aa398748
homepage   : https://github.com/linuxmint/lightdm-settings
license    : GPL-3.0-or-later
component  : system.utils
summary    : A configuration tool for the LightDM display manager
description: |
    A configuration tool for the LightDM display manager. This tool currently lets users configure slick-greeter.
rundeps    :
    - hicolor-icon-theme
    - python-setproctitle
    - python-xapp
    - slick-greeter
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr
    install -Dm00664 $pkgfiles/lightdm-gtk-greeter.conf $installdir/etc/lightdm/lightdm.conf
    cp -R usr $installdir
