name       : lightdm-settings
version    : 1.6.1
release    : 18
source     :
    - https://github.com/linuxmint/lightdm-settings/archive/refs/tags/1.6.1.tar.gz : 6e7f112fe1648d25cc027731668137202d2c299e0ee9e2ad359ed37d0a9f39ed
homepage   : https://github.com/linuxmint/lightdm-settings
license    : GPL-3.0-or-later
component  : system.utils
summary    : A configuration tool for the LightDM display manager
description: |
    A configuration tool for the LightDM display manager. This tool currently lets users configure slick-greeter.
rundeps    :
    - hicolor-icon-theme
    - python-packaging
    - python-setproctitle
    - python-xapp
    - slick-greeter
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr
    cp -R usr $installdir
    install -Dm00664 $pkgfiles/lightdm-gtk-greeter.conf $installdir/etc/lightdm/lightdm.conf
