name       : lightdm-settings
version    : 1.5.9
release    : 16
source     :
    - https://github.com/linuxmint/lightdm-settings/archive/1.5.9.tar.gz : 93b1d54d0fdb4ee3ab03d3da250308f0c9a91dde5b899e2f1b0e28287ef014c9
homepage   : https://github.com/linuxmint/lightdm-settings
license    : GPL-3.0-or-later
component  : system.utils
summary    : A configuration tool for the LightDM display manager
description: |
    A configuration tool for the LightDM display manager. This tool currently lets users configure slick-greeter.
rundeps    :
    - hicolor-icon-theme
    - python-setproctitle
    - python-xapp
    - slick-greeter
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr
    install -Dm00664 $pkgfiles/lightdm-gtk-greeter.conf $installdir/etc/lightdm/lightdm.conf
    cp -R usr $installdir
