name       : lightdm-settings
version    : 1.2.3
release    : 1
source     :
    - https://github.com/linuxmint/lightdm-settings/archive/1.2.3.tar.gz : 4feecb2fb213bc1a5fe910907bff338cada4bb550d647d7eabd3d6c647d5be00
license    : GPL-3.0-or-later
component  : system.utils
summary    : A configuration tool for the LightDM display manager
description: |
    A configuration tool for the LightDM display manager This tool currently lets users configure slick-greeter.
rundeps    : 
    - hicolor-icon-theme
    - python-gobject
    - python-setproctitle
    - python-xapp
    - slick-greeter
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr
    cp -R usr $installdir
