name       : lightdm-settings
version    : 1.4.2
release    : 9
source     :
    - https://github.com/linuxmint/lightdm-settings/archive/1.4.2.tar.gz : b1dbceb833ee5d7887b66322f0130de94f25e85b4bdfcada32620dae0f404ced
homepage   : https://github.com/linuxmint/lightdm-settings
license    : GPL-3.0-or-later
component  : system.utils
summary    : A configuration tool for the LightDM display manager
description: |
    A configuration tool for the LightDM display manager. This tool currently lets users configure slick-greeter.
rundeps    :
    - hicolor-icon-theme
    - python-setproctitle
    - python-xapp
    - slick-greeter
build      : |
    %make
install    : |
    install -dm00755 $installdir/usr
    install -Dm00664 $pkgfiles/lightdm-gtk-greeter.conf $installdir/etc/lightdm/lightdm.conf
    cp -R usr $installdir
